name: sira
description: "Aplicación web para gestión de aprendices - SIRA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Paquete oficial de Supabase
  supabase_flutter: ^2.8.0

  # Iconos predeterminados de Material
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true